# Generated by Django 2.2 on 2020-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
