# Generated by Django 2.2 on 2020-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200224_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='insta_handler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
