# Generated by Django 2.2.6 on 2020-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200314_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_blocked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
