# Generated by Django 3.0.3 on 2021-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210225_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
