# Generated by Django 3.0.3 on 2021-03-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210303_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acount_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
