# Generated by Django 3.0.3 on 2021-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_acount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acount_id',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
