# Generated by Django 3.0.3 on 2021-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210323_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acount_id',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, unique=True),
        ),
    ]
