# Generated by Django 3.0.3 on 2021-03-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210323_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilepic',
        ),
    ]
