"""
Usage: $ python manage.py shell < createusers.py

"""
from django.contrib.auth.models import User
import pandas as pd
import os
from django.db.utils import IntegrityError
from django.template.loader import render_to_string
from django.core.mail import send_mail, send_mass_mail
from django.contrib.auth.models import User

CSV_FILE = 'test.csv'

def password_generator(size):
    import random
    import string
    chars = string.ascii_lowercase + string.digits
    return ''.join(random.choice(chars) for _ in range(size))

def create_username(firstname, surname):
    username = f'{firstname}_{surname}' 
    return username.lower()

FROM_EMAIL='30works <info@thirty.works>'
EMAIL_SUBJECT = "Your new 30works account is ready"
EMAIL_MESSAGE = """

Dear {},

You're receiving this message because I wanted to say hello and see how you're doing.

Not really. This email was automatically generated by a program.

Just to let you know that your 30works account is set up:

        Username: {}
        Password: {}

You can now log in at https://www.thirty.works/login/ with these credentials. 

After logging in for the first time we advise changing your password to something memorable for security, which you can do by visiting https://www.thirty.works/profile/ and hitting "Change Password".

Your username can also be changed there.

Good luck and we look forward to receiving your works this month.

Best wishes,

The Unfeeling Email Robot 

"""

# read the CSV file
df = pd.read_csv(CSV_FILE)
# datatuple = (
#     (
#         EMAIL_SUBJECT, 
#         EMAIL_MESSAGE.format(df['First Name'][i], create_username(df['First Name'][i], df['Surname'][i]), password_generator(7)), 
#         FROM_EMAIL, 
#         [df['Email'][i]]
#     ) 
#     for i in df.index
# )
# send_mass_mail(datatuple)

for i in df.index:


    try:
        first_name = df['First Name'][i]
        surname = df['Surname'][i]
        email = df['Email'][i]
        username = create_username(first_name, surname)
        password = password_generator(7)
        user = User.objects.create_user(
            username=username, 
            password=password, 
            email=email,
            first_name=first_name,
            last_name=surname
        )
        user.is_superuser = False
        user.is_staff = False
        user.save()

        print(f'Created User: {username}\nEmail: {email}\nPass: {password}\n==========')

        send_mail(
            subject=EMAIL_SUBJECT,
            from_email=FROM_EMAIL,
            message=EMAIL_MESSAGE.format(first_name, username, password),
            recipient_list=[email]
        )

    except IntegrityError as ie:
        print(ie)
        print(f'Unable to create User: {username}\nEmail: {email}\nPass: {password}\n==========')

print('done!')





# for i, row in df.iterrows():
#     username = row['First Name'] + '_' + row['Surname']
#     email_address = row['Email Address']
#     password = id_generator(10)
#     try:
#         user = User.objects.create_user(username=username, password=password, email=email_address)
#         user.is_superuser = False
#         user.is_staff = False
#         user.save()

#         print('Created User: {}\nEmail: {}\nPass: {}\n=========='.format(username, email_address, password))

#         email_message = "{}".format(EMAIL_MESSAGE)
#         email_message = email_message.format(username, password)
#         email(EMAIL_SUBJECT, email_message, [email_address])

#     except IntegrityError as ie:
#         print(ie)
#         print('Couldnt create User: {}\nEmail: {}\nPass: {}\n=========='.format(username, email_address, password))
