# Generated by Django 2.2.6 on 2020-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='suggestion',
            field=models.CharField(default='Play with puppy.', max_length=200),
        ),
    ]
