# Generated by Django 2.2 on 2020-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_day_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='suggestion',
        ),
    ]
