# Generated by Django 2.2.6 on 2020-02-29 21:55

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_day_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, default='default_profilepic.png', null=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postvideo',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
