# Generated by Django 2.2.6 on 2020-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200229_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
