# Generated by Django 2.2.6 on 2020-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200301_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, default='default_profilepic.png', null=True, upload_to='post_pics'),
        ),
    ]
