# Generated by Django 2.2 on 2020-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200314_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anything_else',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
