# Generated by Django 2.2.6 on 2020-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200324_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anything_else',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
