# Generated by Django 2.2.6 on 2020-03-27 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200325_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
