# Generated by Django 3.0.3 on 2021-03-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210321_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['number']},
        ),
    ]
