# Generated by Django 3.0.3 on 2021-03-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210327_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
