# Generated by Django 3.0.3 on 2021-03-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, max_length=2001, null=True),
        ),
    ]
