# Generated by Django 3.0.3 on 2021-03-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210327_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
