# Generated by Django 3.0.3 on 2021-03-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210327_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
